version: 2
jobs:
 build:
  docker:
   - image: circleci/node:10.16

  working_directory: ~/client

  steps:
   - checkout
   - restore_cache:
      keys:
       - v1-dependencies-{{ checksum "package.json" }}
       - v1-dependencies-
   - run: npm install
   - save_cache:
      paths:
       - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}

 deploy:
  machine:
   enabled: true

  working_directory: ~/client

  steps:
   - add_ssh_keys:
      fingerprints:
       - "32:fa:a6:f2:d8:27:83:fb:38:13:24:ed:4f:d0:6d:ff"
   - checkout
   - run:
      name: Push Main to Production
      command: |
       git push https://github.com/ujjawalsidhpura/MaintenancePro.git main:production

workflows:
 version: 2
 test_and_deploy:
  jobs:
   - build:
      filters:
       branches:
        ignore: production
   - deploy:
      filters:
       branches:
        ignore: production
      requires:
       - build
